/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Fri, 13 Jan 2023 01:56:05 GMT
///
export { request } from '../sdk-interface';
