/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Fri, 13 Jan 2023 01:56:05 GMT
///
/// Parent module: appModule
/// Controller: "appController" registered as "appController" (1 routes)

import { request } from '../central';

export default {
  // GET @ api-status
  getApiStatus(
    params: {} = {},
    body: {} = {},
    query: {} = {},
  ): Promise<object> {
    return request('GET', `api-status`, body, query);
  },
};
