/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Fri, 13 Jan 2023 01:56:05 GMT
///
/// Parent module: appModule
/// Controller: "characterController" registered as "characterController" (3 routes)

import { request } from '../central';
import type {
  Info,
  Character,
} from '../_types/_external2/node_modules/rickmortyapi/dist/interfaces';

export default {
  // GET @ rick-and-morty-characters
  getRickAndMortyCharacters(
    params: {} = {},
    body: {} = {},
    query: {} = {},
  ): Promise<Info<Character[]>> {
    return request('GET', `rick-and-morty-characters`, body, query);
  },

  // GET @ rick-and-morty-character/:id
  getRickAndMortyCharacterById(
    params: { id: number },
    body: {} = {},
    query: {} = {},
  ): Promise<Character> {
    return request('GET', `rick-and-morty-character/${params.id}`, body, query);
  },

  // GET @ rick-and-morty-characters-filtered
  getRickAndMortyCharactersByQuery(
    params: {} = {},
    body: {} = {},
    query: {} = {},
  ): Promise<Info<Character[]>> {
    return request('GET', `rick-and-morty-characters-filtered`, body, query);
  },
};
