/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Fri, 13 Jan 2023 01:56:05 GMT
///
/// Module name: appModule

export { default as appController } from './appController';
export { default as characterController } from './characterController';
